CREATE TABLE "ClubMatchDetails" (
	"_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"mongoId" text,
	"Club" text,
	"Fixture" text,
	"Possession" integer DEFAULT 0 NOT NULL,
	"Goals" integer DEFAULT 0 NOT NULL,
	"ShotsOnTarget" integer DEFAULT 0 NOT NULL,
	"ShotsOffTarget" integer DEFAULT 0 NOT NULL,
	"Fouls" integer DEFAULT 0 NOT NULL,
	"YellowCards" integer DEFAULT 0 NOT NULL,
	"RedCards" integer DEFAULT 0 NOT NULL,
	"Passes" integer DEFAULT 0 NOT NULL,
	"PlayerStats" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"Won" boolean DEFAULT false NOT NULL,
	"Drew" boolean DEFAULT false NOT NULL,
	"Events" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"createdAt" timestamp (3) DEFAULT now() NOT NULL,
	"updatedAt" timestamp (3) NOT NULL,
	CONSTRAINT "ClubMatchDetails_mongoId_unique" UNIQUE("mongoId")
);
--> statement-breakpoint
CREATE TABLE "Fixtures" (
	"_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"mongoId" text,
	"Title" text,
	"FixtureCode" text,
	"SeasonCode" text,
	"LeagueCode" text,
	"Week" integer,
	"Season" text,
	"Stadium" text,
	"Played" boolean DEFAULT false NOT NULL,
	"Tie" text,
	"Stage" text DEFAULT 'lg-match' NOT NULL,
	"ReverseFixture" text,
	"PlayedAt" timestamp (3),
	"Home" text,
	"Away" text,
	"HomeTeam" text,
	"AwayTeam" text,
	"Details" jsonb,
	"Events" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"Type" text,
	"HomeSideDetails" text,
	"AwaySideDetails" text,
	"HomeManager" text,
	"AwayManager" text,
	"isFinalMatch" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp (3) DEFAULT now() NOT NULL,
	"updatedAt" timestamp (3) NOT NULL,
	CONSTRAINT "Fixtures_mongoId_unique" UNIQUE("mongoId")
);
--> statement-breakpoint
CREATE TABLE "PlayerMatchDetails" (
	"_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"mongoId" text,
	"Player" text,
	"Fixture" text,
	"Goals" integer DEFAULT 0 NOT NULL,
	"Saves" integer DEFAULT 0 NOT NULL,
	"YellowCards" integer DEFAULT 0 NOT NULL,
	"Fouls" integer DEFAULT 0 NOT NULL,
	"RedCards" integer DEFAULT 0 NOT NULL,
	"Passes" integer DEFAULT 0 NOT NULL,
	"Tackles" integer DEFAULT 0 NOT NULL,
	"Assists" integer DEFAULT 0 NOT NULL,
	"CleanSheets" integer DEFAULT 0 NOT NULL,
	"Points" integer DEFAULT 0 NOT NULL,
	"Dribbles" integer DEFAULT 0 NOT NULL,
	"Interceptions" integer DEFAULT 0 NOT NULL,
	"Form" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp (3) DEFAULT now() NOT NULL,
	"updatedAt" timestamp (3) NOT NULL,
	CONSTRAINT "PlayerMatchDetails_mongoId_unique" UNIQUE("mongoId")
);
--> statement-breakpoint
CREATE TABLE "Players" (
	"_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"mongoId" text,
	"FirstName" text NOT NULL,
	"LastName" text NOT NULL,
	"Nationality" text,
	"Age" integer,
	"PlayerID" text,
	"Position" text,
	"Role" text,
	"PositionNumber" integer,
	"Attributes" jsonb,
	"Rating" integer,
	"ShirtNumber" text,
	"Value" integer,
	"Form" integer DEFAULT 6 NOT NULL,
	"isReserve" boolean DEFAULT false NOT NULL,
	"Appearance" jsonb,
	"TransferHistory" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"RatingsHistory" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"isSigned" boolean DEFAULT false NOT NULL,
	"ClubCode" text,
	"Club" text,
	"createdAt" timestamp (3) DEFAULT now() NOT NULL,
	"updatedAt" timestamp (3) NOT NULL,
	CONSTRAINT "Players_mongoId_unique" UNIQUE("mongoId"),
	CONSTRAINT "Players_PlayerID_unique" UNIQUE("PlayerID")
);
