ALTER TABLE "Clubs" ADD COLUMN IF NOT EXISTS "Lineup" jsonb;
ALTER TABLE "Clubs" ADD COLUMN IF NOT EXISTS "Tactic" jsonb;
ALTER TABLE "Clubs" ADD COLUMN IF NOT EXISTS "Finances" jsonb;

ALTER TABLE "Players" ADD COLUMN IF NOT EXISTS "Fitness" real NOT NULL DEFAULT 100;
ALTER TABLE "Players" ADD COLUMN IF NOT EXISTS "Injury" jsonb;
